"""add photo_url to doctor_profile

Revision ID: a5c71f1d4a9b
Revises: 854212df7141
Create Date: 2026-04-20 13:26:58.771656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c71f1d4a9b'
down_revision: Union[str, None] = '854212df7141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_profiles', 'photo_url')
    # ### end Alembic commands ###
