"""add ward_photos and hospital_photos tables

Revision ID: e845b72042dd
Revises: a5c71f1d4a9b
Create Date: 2026-04-20 15:35:26.688911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e845b72042dd'
down_revision: Union[str, None] = 'a5c71f1d4a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_photos_category'), 'hospital_photos', ['category'], unique=False)
    op.create_index(op.f('ix_hospital_photos_id'), 'hospital_photos', ['id'], unique=False)
    op.create_table('ward_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_photos_id'), 'ward_photos', ['id'], unique=False)
    op.create_index(op.f('ix_ward_photos_ward_id'), 'ward_photos', ['ward_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ward_photos_ward_id'), table_name='ward_photos')
    op.drop_index(op.f('ix_ward_photos_id'), table_name='ward_photos')
    op.drop_table('ward_photos')
    op.drop_index(op.f('ix_hospital_photos_id'), table_name='hospital_photos')
    op.drop_index(op.f('ix_hospital_photos_category'), table_name='hospital_photos')
    op.drop_table('hospital_photos')
    # ### end Alembic commands ###
